### ISSUE TITLE
Startup crash for newest EntityCulling version (v2.1.4) for Minecraft v1.16.5

### ISSUE THREAD

**Issue by sdarkwell** [Meldexun/EntityCulling#25]
**Hello,**

I am experiencing a crash on startup using the newest version of EntityCulling (v2.1.4) for Minecraft v1.16.5.

No other mods are installed, and EntityCulling is using its default configuration.

**Crashlog:**

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/27/21 7:20 PM
Description: Initializing game

java.lang.IllegalArgumentException: null
	at org.objectweb.asm.Frame.getAbstractTypeFromDescriptor(Frame.java:374) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.Frame.push(Frame.java:552) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.Frame.execute(Frame.java:1019) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.MethodWriter.visitFieldInsn(MethodWriter.java:999) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.FieldInsnNode.accept(FieldInsnNode.java:88) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.0.jar:9.0] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242] {}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:474) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.24.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.objectweb.asm.Frame.getAbstractTypeFromDescriptor(Frame.java:374) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.Frame.push(Frame.java:552) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.Frame.execute(Frame.java:1019) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.MethodWriter.visitFieldInsn(MethodWriter.java:999) ~[asm-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.FieldInsnNode.accept(FieldInsnNode.java:88) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:144) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:751) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.0.jar:9.0] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.0.jar:9.0] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242] {}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:474) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.24.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 750495160 bytes (715 MB) / 2133852160 bytes (2035 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.24.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.24
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.24-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.24-universal.jar                |Forge                         |forge                         |36.1.24             |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		EntityCulling-1.16.5-2.1.4.jar                    |Entity Culling                |entity_culling                |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 20063485-7979-46a1-bf26-0a04a65d3875
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.27, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 1800X Eight-Core Processor

**Comment by Meldexun** [comment]
Fixed in v1.16.5-2.1.5
