### ISSUE TITLE
Not sure if this is a bug

### ISSUE THREAD

**Issue by ModernGamingWorld** [Meldexun/EntityCulling#30]
20:56:41] [main/ERROR]: Error occurred applying transform of coremod entity_culling/UpdateCameraAndRenderTransformer.js function UpdateCameraAndRender Transformer
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.indexOf(InsnList.java:133) ~[asm-tree-9.0.jar:9.0]
	at jdk.nashorn.internal.scripts.Script$Recompilation$196$1102A$\^eval\_.initializeCoreMod$transformer(<eval>:31) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.NashornFactory$$Lambda$410/208236934.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$444/1854597758.buildTransformedClassNodeFor(Unknown Source) [modlauncher-8.0.9.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:214) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.getClassNode(MixinLaunchPlugin.java:202) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1843) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1007) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:997) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:885) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:730) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:650) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) [mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.32.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/1943524982.call(Unknown Source) [forge-1.16.5-36.1.32.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by Meldexun** [comment]
Please use the issue template and provide the requested information.
